export const REQUEST_TOP_STATES = 'REQUEST_TOP_STATES';
export const FETCH_TOP_STATES = 'FETCH_TOP_STATES';
export const RECEIVE_TOP_STATES = 'RECEIVE_TOP_STATES';
export const INVALIDATE_TOP_STATES = 'INVALIDATE_TOP_STATES';
export const SELECT_SORTFIELD = 'SELECT_SORTFIELD';

export const REQUEST_COMPANY_COMPLAINTS = 'REQUEST_COMPANY_COMPLAINTS';
export const RECEIVE_COMPANY_COMPLAINTS = 'RECEIVE_COMPANY_COMPLAINTS';

export const REQUEST_PRODUCT_COMPLAINTS = 'REQUEST_PRODUCT_COMPLAINTS';
export const RECEIVE_PRODUCT_COMPLAINTS = 'RECEIVE_PRODUCT_COMPLAINTS';

export const RECEIVE_STATE_PROFILES = 'RECEIVE_STATES_PROFILES';
export const REQUEST_STATE_PROFILES = 'REQUEST_STATES_PROFILES';

export const RECEIVE_PRODUCT_DETAILS = 'RECEIVE_PRODUCT_DETAILS';
export const REQUEST_PRODUCT_DETAILS = 'REQUEST_PRODUCT_DETAILS';

export const RECEIVE_COMPANY_DETAILS = 'RECEIVE_COMPANY_DETAILS';
export const REQUEST_COMPANY_DETAILS = 'REQUEST_COMPANY_DETAILS';

export const SWITCH_UI_TO_STATE_CENTRIC = "SWITCH_UI_TO_STATE_CENTRIC";
export const SWITCH_UI_TO_PRODUCT_CENTRIC = "SWITCH_UI_TO_PRODUCT_CENTRIC";
export const SWITCH_UI_TO_COMPANY_CENTRIC = "SWITCH_UI_TO_COMPANY_CENTRIC";

export const CLEAR_COMPLAINT_DETAILS = "CLEAR_COMPLAINT_DETAILS";
export const INVALIDATE_COMPLAINT_DATA = "INVALIDATE_COMPLAINT_DATA";

export const RECEIVE_CENSUS_IMPORT_STATUS = "RECEIVE_CENSUS_IMPORT_STATUS";
export const RECEIVE_COMPLAINTS_IMPORT_STATUS = "RECEIVE_COMPLAINTS_IMPORT_STATUS"
export const REQUEST_CENSUS_IMPORT_STATUS = "REQUEST_CENSUS_IMPORT_STATUS"
export const REQUEST_COMPLAINT_IMPORT_STATUS = "REQUEST_COMPLAINT_IMPORT_STATUS"
